(package "jenkinsfile-mode"
         "0.0.1"
         "Major mode for editing Jenkins declarative pipeline syntax")

(website-url "https://github.com/elp-revive/jenkinsfile-mode")
(keywords "")

(package-file "buffer-move.el")

(source "melpa")

(depends-on "emacs" "24.1")
(depends-on "groovy-mode" "2.0")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
